- name: install
  become: yes
  pacman:
    name:
      - zsh
      - ripgrep
      - fd
      - fzf
      - exa
    state: present

- name: check if OMZ folder exists
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: stat

- name: install oh-my-zsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not stat.stat.exists

- name: copy theme
  vars:
    path_color: "{{ zsh_path_color }}"
  template:
    src: robbyrussell-mod.zsh-theme
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/robbyrussell-mod.zsh-theme"

- name: enable theme
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: ^ZSH_THEME=
    line: ZSH_THEME="robbyrussell-mod"

- name: copy options
  copy:
    src: managed-custom-options.zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/managed-custom-options.zsh"

- name: change shell
  become: yes
  command: "chsh -s /bin/zsh {{ ansible_user }}"

- name: check if OMZ folder exists as root
  become: yes
  stat:
    path: "/root/.oh-my-zsh"
  when: copy_user_config_for_root
  register: stat

- name: install oh-my-zsh as root
  become: yes
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: copy_user_config_for_root and not stat.stat.exists

- name: copy theme as root
  become: yes
  vars:
    path_color: "{{ zsh_path_color_root }}"
  template:
    src: robbyrussell-mod.zsh-theme
    dest: "/root/.oh-my-zsh/custom/themes/robbyrussell-mod.zsh-theme"
  when: copy_user_config_for_root

- name: enable theme as root
  become: yes
  lineinfile:
    path: "/root/.zshrc"
    regexp: ^ZSH_THEME=
    line: ZSH_THEME="robbyrussell-mod"
  when: copy_user_config_for_root

- name: copy options as root
  become: yes
  copy:
    src: managed-custom-options.zsh
    dest: "/root/.oh-my-zsh/custom/managed-custom-options.zsh"
  when: copy_user_config_for_root

- name: change shell as root
  become: yes
  command: "chsh -s /bin/zsh root"
  when: copy_user_config_for_root
