- name: install roles
  hosts: all
  roles:
    - role: ufw
      tags: ufw
    - role: sshd
      tags: sshd
    - role: nvim
      tags: nvim
    - role: nvim-symlinks
      tags: nvim-symlinks
    - role: zsh
      tags: zsh
    - role: aur-helper
      tags: aur-helper

- name: install nvim and zsh plugins for root
  become: yes
  hosts: all
  roles:
    - role: nvim
      tags: nvim
    - role: zsh
      tags: zsh
