- name: install roles
  hosts: all
  roles:
    - nvim
    - nvim-symlinks
    - zsh
    - aur-helper
  
- name: install nvim and zsh plugins for root
  become: yes
  hosts: all
  roles:
    - nvim
    - zsh