- name: Global env vars
  hosts: all
  become: yes
  tasks:
  - name: set vars
    lineinfile:
      path: /etc/environment
      regexp: "^{{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
    loop:
      - { key: "EDITOR", value: "/usr/bin/nvim" }
